name: Flutter Workflow Test

on:
  push:
    branches: [main]

jobs:
  flutter_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Run flutter doctor
        run: flutter doctor